# Generated by Django 3.0.5 on 2021-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=200)),
                ('api_price', models.FloatField()),
                ('cli_price', models.FloatField(max_length=10)),
                ('region', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('pay_as_you_go_price', models.FloatField()),
                ('one_year_reserved_price', models.FloatField()),
                ('three_year_reserved_price', models.FloatField()),
                ('per_saving_paygo', models.CharField(max_length=200)),
                ('per_saving_one', models.CharField(max_length=200)),
                ('per_saving_three', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'SpotPrice',
                'verbose_name_plural': 'SpotPrices',
            },
        ),
    ]
