# Generated by Django 3.0.5 on 2021-06-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotprices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotprices',
            name='api_price',
            field=models.FloatField(default=float("-inf")),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='cli_price',
            field=models.FloatField(default=float("-inf")),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='one_year_reserved_price',
            field=models.FloatField(default=float("-inf")),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='pay_as_you_go_price',
            field=models.FloatField(default=float("-inf")),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='per_saving_one',
            field=models.FloatField(default=float("-inf")),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='per_saving_paygo',
            field=models.FloatField(default=float("-inf")),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='per_saving_three',
            field=models.FloatField(default=float("-inf")),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='three_year_reserved_price',
            field=models.FloatField(default=float("-inf")),
        ),
    ]
