# Generated by Django 3.0.5 on 2021-06-17 19:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotprices', '0002_auto_20210615_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvictionNotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('vm_name', models.CharField(max_length=200)),
                ('vm_region', models.CharField(max_length=200)),
                ('cluster_name', models.CharField(max_length=200)),
                ('cluster_region', models.CharField(max_length=200)),
                ('eviction_time', models.CharField(max_length=200)),
                ('eviction_notice', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='spotprices',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
