# Generated by Django 3.0.5 on 2021-06-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotprices', '0003_auto_20210617_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='evictionnotices',
            name='vm_size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
