# Generated by Django 3.0.5 on 2021-06-21 21:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotprices', '0004_evictionnotices_vm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionnotices',
            name='cluster_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='cluster_region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='eviction_notice',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='eviction_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='start_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='vm_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='vm_region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evictionnotices',
            name='vm_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
