# Generated by Django 3.0.5 on 2021-06-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotprices', '0005_auto_20210621_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='evictionnotices',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
