# Generated by Django 3.0.5 on 2021-06-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotprices', '0006_evictionnotices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionnotices',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
